<<<<<<< Updated upstream
stages:
  - test
=======
name: githubactionss
>>>>>>> Stashed changes

e2e_mcp:
  image: mcr.microsoft.com/playwright:latest
  stage: test
  script:
    - npm ci
    - npx playwright install --with-deps        # install browsers
    - npx playwright launch --server --port 9222 --headless &  # start MCP server :contentReference[oaicite:1]{index=1}
    - npx mcp run --feature features/login.feature --endpoint ws://localhost:9222
