stages:
  - test

variables:
  NODE_VERSION: "18"
  MCP_PORT: "9323"

cache:
  paths:
    - node_modules/

before_script:
  # Use the node image and install dependencies once
  - apt-get update && apt-get install -y curl
  - curl -fsSL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
  - npm ci
  - npx playwright install

mcp-playwright-test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    # 1. Start MCP Server in headless mode, listening on MCP_PORT
    - npx @playwright/mcp@latest --headless --port $MCP_PORT &
    # give MCP a moment to start
    - sleep 5
    # 2. Run your Playwright tests; they should be configured to point at http://localhost:$MCP_PORT/sse
    - npx playwright test
  artifacts:
    when: always
    reports:
      junit: playwright-report/junit.xml
    paths:
      - playwright-report/
      - test-results/
