name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  ci_cd_workflow:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository to ensure package.json is available
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Step 3: Clean npm cache to avoid potential issues
    - name: Clean npm cache
      run: npm cache clean --force  # Clear npm cache

    # Step 4: Update npm to the latest stable version
    - name: Update npm to latest stable version
      run: npm install -g npm@latest  # Install latest npm

    # Step 5: List files for debugging (Optional step to check the directory structure)
    - name: List files for debugging
      run: ls -la /home/runner/work/MCP-Repo/MCP-Repo

    # Step 6: Install dependencies using npm ci
    - name: Install dependencies
      run: npm ci  # Install dependencies from package-lock.json

    # Step 7: Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npm run install:browsers  # Install necessary browsers for Playwright

    # Step 8: Run MCP tests
    - name: Run MCP Tests
      run: npm run test:mcp  # Run the MCP tests using your custom script

    # Optional: Add success message after tests
    - name: Send success message
      run: echo "CI/CD workflow executed successfully! Hello ${{ inputs.name }}"
